import { writeFile } from "fs/promises";
import { join } from "path";
import { zodToJsonSchema } from "zod-to-json-schema";
import { DIRNAME } from "./src/config";
import { fixturesSchema } from "./src/schemas";

for (const [filename, schema] of Object.entries({
	"fixture-schema.jsonc": fixturesSchema,
})) {
	const contents = `// AUTOMATICALLY GENERATED BY \`scripts/generate-schemas.ts\`
// DO NOT EDIT THIS FILE DIRECTLY

${JSON.stringify(zodToJsonSchema(schema), null, 2)}`;

	await writeFile(join(DIRNAME, "schemas", filename), contents);
}
